version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - C-enhancement
  ignore:
  - dependency-name: proc-macro2
    versions:
    - ">= 1.0.a, < 1.1"
  - dependency-name: quote
    versions:
    - ">= 1.0.a, < 1.1"
  - dependency-name: syn
    versions:
    - ">= 1.0.a, < 1.1"
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.2.0
    - 1.3.0
    - 1.4.0
  - dependency-name: which
    versions:
    - 4.1.0
  - dependency-name: uom
    versions:
    - 0.31.0
    - 0.31.1
  - dependency-name: nix
    versions:
    - 0.20.0
  - dependency-name: once_cell
    versions:
    - 1.6.0
    - 1.7.0
  - dependency-name: ordered-float
    versions:
    - 2.1.0
  - dependency-name: raw-cpuid
    versions:
    - 9.0.0
  - dependency-name: async-std
    versions:
    - 1.9.0
  - dependency-name: platforms
    versions:
    - 1.1.0
