stages:
    - stage: lints
      displayName: Lints
      dependsOn: []
      jobs:
          - job: lints
            displayName: rustfmt and clippy
            continueOnError: true
            pool:
                vmImage: ubuntu-16.04
            steps:
                - template: install-rust.yml
                  parameters:
                      toolchain: nightly

                - script: |
                      rustup component add rustfmt --toolchain nightly
                      cargo +nightly fmt -- --check
                  displayName: Run rustfmt
                  continueOnError: true

                - script: |
                      rustup component add clippy --toolchain nightly
                      cargo +nightly clippy --all-targets --all-features -- -D warnings
                  displayName: Run clippy
                  continueOnError: true
